@startuml

CatalogDao -> RemoveBookFromCatalogActivity : removeBookFromCatalog

RemoveBookFromCatalogActivity -> RemoveBookFromCatalogActivity : execute
alt
RemoveBookFromCatalogActivity -> CatalogDao : BookNotFoundException
end
RemoveBookFromCatalogActivity -> CatalogDao : RemoveBookFromCatalogResponse

@enduml